# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Solidity contract build and test

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  core-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Build and test Solidity contracts
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd contracts && npm install && npm ci
      - run: cd contracts && npx hardhat compile
      - run: cd contracts && npx hardhat test
